apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapi-deployment
  labels:
    app: dotnetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetapi
  template:
    metadata:
      labels:
        app: dotnetapi
    spec:
      containers:
      - name: dotnetapi
        image: kubraakesici/dotnet-api:1.5
        ports:
        - containerPort: 5000
        env:
        - name: JWT_SECURITY_KEY
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: jwt-security-key
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: db-server
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: db-password
        - name: ELK_BASE_URL
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: elk-base-url
        - name: ELK_DEFAULT_IND
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: elk-default-ind
        - name: ELK_USERNAME
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: elk-username
        - name: ELK_PASS
          valueFrom:
            secretKeyRef:
              name: dotnetapi-secret
              key: elk-password
          
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapi-service
spec:
  type: NodePort
  selector:
    app: dotnetapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30102