apiVersion: v1
kind: Secret
metadata:
  name: dotnetapi-secret
type: Opaque
data:
  db-password: QWRlc3NvMTIzNDU2IQ==
  jwt-security-key: d2Vzb2NpZXR5c2VjdXJpdHlrZXk=
  db-server: MTAuNTguMTY4LjU2
  db-name: V2VTb2NpZXR5RGI=
  db-user: c2E=
  elk-base-url: aHR0cDovL2xvY2FsaG9zdDo5MjAw
  elk-default-ind: QXJ0aWNsZQ==
  elk-username: ZWxhc3RpYw==
  elk-password: MTIzNDU2